const LEANSER_ENABLE_ENV_VAR_NAME = 'LEANSER_ENABLE';
const LEANSER_DEBUG_ENABLE_ENV_VAR_NAME = 'LEANSER_DEBUG_ENABLE';

const LEANSER_ENABLED =
    (process.env[LEANSER_ENABLE_ENV_VAR_NAME] || 'true') === 'true';
const LEANSER_DEBUG_ENABLED =
    (process.env[LEANSER_DEBUG_ENABLE_ENV_VAR_NAME] || 'false') === 'true';

module.exports = {
    LEANSER_ENABLE_ENV_VAR_NAME,
    LEANSER_DEBUG_ENABLE_ENV_VAR_NAME,

    LEANSER_ENABLED,
    LEANSER_DEBUG_ENABLED,
};
