name: AWS Lambda Layer Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.2
        with:
          version: 2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Release AWS Lambda Layer
        run: ./scripts/release-layer.sh
